bcgov/sheriff-scheduling

.github/CODEOWNERS
.github/workflows/api-dotnetcore.yml
.github/workflows/app-react.yml
.github/workflows/app-vue.yml
api/api.csproj
web/package-lock.json

Github actions will validate that the code builds and the backend tests pass before a PR can be accepted.
api project guid should resolve the pipeline issue in Openshift.

Github actions, project GUID

---

web/src/components/MyTeam/Tabs/AddComponents/AddLocation.vue
web/src/components/MyTeam/Tabs/AddForms/AddLocationForm.vue
web/src/components/MyTeam/Tabs/LeaveTab.vue
web/src/components/MyTeam/Tabs/LocationTab.vue
web/src/components/MyTeam/Tabs/RoleAssignmentTab.vue
web/src/components/MyTeam/Tabs/TrainingTab.vue

Changes include: 
- SS-197: Adding functionality to edit the locations 
- Applying PR suggestions: 
- Displaying confirmation message for changing the home Location 
- Moving the home Location field to the identification tab

SS-197: enabling edit locations

---

web/src/components/MyTeam/Tabs/AddForms/AddLocationForm.vue
web/src/components/MyTeam/Tabs/IdentificationTab.vue
web/src/components/MyTeam/Tabs/LeaveTab.vue
web/src/components/MyTeam/Tabs/LocationTab.vue
web/src/components/MyTeam/Tabs/TrainingTab.vue

Refer to https://github.com/bcgov/sheriff-scheduling/pull/23 for details.

Enable editing of location assignments

---

api/infrastructure/authorization/PermissionFiltersExtensions.cs
api/models/dto/UnassignRoleDto.cs
api/services/usermanagement/SheriffService.cs
api/services/usermanagement/UserService.cs
web/src/components/MyTeam/MyTeamMembers.vue
web/src/components/MyTeam/Tabs/AddForms/AddLeaveForm.vue
web/src/components/MyTeam/Tabs/AddForms/AddLocationForm.vue
web/src/components/MyTeam/Tabs/AddForms/AddRoleForm.vue
web/src/components/MyTeam/Tabs/AddForms/AddTrainingForm.vue
web/src/components/MyTeam/Tabs/IdentificationTab.vue
web/src/components/MyTeam/Tabs/RoleAssignmentTab.vue
web/src/components/MyTeam/Tabs/UserSummaryTemplate.vue

Updates to My Team and Profile Screens

---

api/controllers/usermanagement/SheriffController.cs
api/models/dto/UnassignRoleDto.cs
api/models/dto/generated/SheriffDto.g.cs
api/services/usermanagement/SheriffService.cs
api/services/usermanagement/UserService.cs
db/migrations/20201026182905_PhotoUpdateField.Designer.cs
db/migrations/20201026182905_PhotoUpdateField.cs
db/models/sheriff/Sheriff.cs
web/vue.config.js

Image caching fix, cache images for 6 months.. provide an url with a timestamp in it.

Image caching fix

---

api/services/usermanagement/SheriffService.cs
web/src/components/ManageTypes/AddAssignmentForm.vue
web/src/components/ManageTypes/AssignmentTypes.vue

Changes include:
- SS-120: Added functionality to add assignment types
- SS-121: Added functionality to change the sort order of assignment types
- SS-414: Added functionality to edit assignment types
- SS-125: Added functionality to view a list of assignments in the "Assignment types" page
- Changes based on feedback received through Sprint Demo:
- Change "delete" button in confirm-delete pop-up windows to "confirm"
- Enable displaying 50 users per page in the profile list
- Changes based on latest API changes for timezone: Including the timezone string for SheriffAwayLocation, SheriffLeave,SheriffTraining POST/PUT
- Bug fix for modals resetting information before hiding

SS-120, SS-121, SS-414 and SS-125: Added functionality to add, edit, view and sort assignment types

---

api/controllers/scheduling/ShiftController.cs
api/helpers/extensions/SheriffExtensions.cs
api/models/dto/generated/AddAssignmentDto.g.cs
api/models/dto/generated/AssignmentDto.g.cs
api/models/dto/generated/UpdateAssignmentDto.g.cs
api/services/scheduling/ShiftService.cs
db/migrations/20201112191625_StartEndTimespanForAssignment.Designer.cs
db/migrations/20201112191625_StartEndTimespanForAssignment.cs
db/models/scheduling/Assignment.cs
tests/controllers/ShiftControllerTests.cs
tests/db/AssignmentOverlapTests.cs
web/src/components/ShiftSchedule/ManageSchedule.vue
web/src/components/ShiftSchedule/components/ScheduleHeader.vue
web/src/components/ShiftSchedule/components/TeamMemberCard.vue

Plus improvements to handle conflicts while adding shifts.  Refer to https://github.com/bcgov/sheriff-scheduling/pull/39 for details.

Add support for importing shifts

---

web/src/components/DutyRoster/DutyRoster.vue
web/src/components/ManageTypes/AssignmentTypes.vue
web/src/components/ManageTypes/LeaveTrainingTypes.vue
web/src/router/index.ts

- Changing the wording and icon for expiring manage Types items
- Changed the default view for duty roster to display the fuel gauge

Changes based on feedback received on SS-135, SS-123, SS-134 and SS-492

---

web/package-lock.json
web/src/components/DutyRoster/DutyRoster.vue
web/src/components/DutyRoster/components/DutyCard.vue
web/src/components/DutyRoster/components/DutyRosterHeader.vue
web/src/components/DutyRoster/components/SheriffAvailabilityCard.vue
web/src/components/DutyRoster/components/SheriffFuelGauge.vue
web/src/styles/_custom.scss
web/src/types/DutyRoster/index.ts

Refer to https://github.com/bcgov/sheriff-scheduling/pull/48 for details.

Add support for assigning team members to duties

---

api/appsettings.json
api/controllers/scheduling/DutyRosterController.cs
api/models/dto/generated/AddShiftDto.g.cs
api/models/dto/generated/ShiftDto.g.cs
api/models/dto/generated/UpdateShiftDto.g.cs
api/services/scheduling/DistributeScheduleService.cs
api/services/scheduling/DutyRosterService.cs
api/services/scheduling/ShiftService.cs
common/helpers/extensions/DateTimeOffsetExtensions.cs
db/migrations/20201127194914_OvertimeHours.Designer.cs
db/migrations/20201127194914_OvertimeHours.cs
db/models/scheduling/Shift.cs
db/models/scheduling/notmapped/ShiftAvailability.cs
docker/manage
tests/controllers/DutyRosterControllerTests.cs
tests/controllers/ShiftControllerTests.cs
web/package-lock.json
web/src/components/DutyRoster/DutyRoster.vue
web/src/components/DutyRoster/DutyRosterDayView.vue
web/src/components/DutyRoster/DutyRosterWeekView.vue
web/src/components/DutyRoster/components/DutyCardWeekView.vue
web/src/components/DutyRoster/components/DutyRosterAssignment.vue
web/src/components/DutyRoster/components/DutyRosterHeader.vue
web/src/components/DutyRoster/components/DutyRosterTeamMemberCard.vue
web/src/components/ShiftSchedule/components/DistributeHeader.vue
web/src/types/DutyRoster/index.ts

Refer to https://github.com/bcgov/sheriff-scheduling/pull/55 for details.

Initial iteration of the weekly view for the duty roster page

---

api/infrastructure/authorization/ClaimsService.cs
api/services/scheduling/DutyRosterService.cs
web/src/components/DutyRoster/components/DutyCard.vue
web/src/components/DutyRoster/components/DutyRosterHeader.vue
web/src/components/ManageTypes/AssignmentTypes.vue
web/src/components/ManageTypes/LeaveTrainingTypes.vue
web/src/components/MyTeam/DefineRolesAccess.vue
web/src/components/MyTeam/MyTeamMembers.vue
web/src/components/NavigationTopbar.vue
web/src/components/ShiftSchedule/ManageSchedule.vue
web/src/components/ShiftSchedule/components/DistributeHeader.vue
web/src/components/ShiftSchedule/components/ScheduleCard.vue
web/src/components/ShiftSchedule/components/ScheduleHeader.vue
web/src/components/ShiftSchedule/components/TeamMemberCard.vue
web/src/types/ShiftSchedule/index.ts

refer to https://github.com/bcgov/sheriff-scheduling/pull/57 for details

Add support for moving a sheriff from one duty to another if it ends early, and for tracking overtime on the manage-schedule page

---

web/package-lock.json
web/src/components/DutyRoster/DutyRoster.vue
web/src/components/DutyRoster/DutyRosterDayView.vue
web/src/components/DutyRoster/DutyRosterWeekView.vue
web/src/components/DutyRoster/components/AddDutySlotWeekForm.vue
web/src/components/DutyRoster/components/DutyCardWeekView.vue
web/src/components/DutyRoster/components/DutyRosterAssignment.vue
web/src/components/DutyRoster/components/DutyRosterTeamMemberCard.vue
web/src/components/ShiftSchedule/DistributeSchedule.vue
web/src/components/ShiftSchedule/components/DistributeHeader.vue
web/src/types/DutyRoster/index.ts

refer to https://github.com/bcgov/sheriff-scheduling/pull/59 for details

Add support for editing and deleting assignments and duties, and associating team-members and duties in the duty-roster weekly view.

---

api/controllers/ManageTypesController.cs
api/controllers/scheduling/DutyRosterController.cs
api/services/scheduling/DutyRosterService.cs
db/configuration/PermissionConfiguration.cs
db/migrations/20201207193540_RemoveViewManagedTypes.Designer.cs
db/migrations/20201207193540_RemoveViewManagedTypes.cs
db/models/auth/Permission.cs
tests/controllers/DutyRosterControllerTests.cs
tests/controllers/RoleControllerTests.cs
web/src/App.vue
web/src/components/DutyRoster/DutyRoster.vue
web/src/components/DutyRoster/DutyRosterDayView.vue
web/src/components/DutyRoster/DutyRosterWeekView.vue
web/src/components/DutyRoster/components/DutyCard.vue
web/src/components/DutyRoster/components/DutyCardWeekView.vue
web/src/components/DutyRoster/components/DutyRosterAssignment.vue
web/src/components/DutyRoster/components/DutyRosterHeader.vue
web/src/components/DutyRoster/components/SheriffAvailabilityCard.vue
web/src/components/DutyRoster/components/SheriffFuelGauge.vue
web/src/components/ManageTypes/AssignmentTypes.vue
web/src/components/ManageTypes/LeaveTrainingTypes.vue
web/src/components/NavigationTopbar.vue
web/src/components/ShiftSchedule/DistributeSchedule.vue
web/src/components/ShiftSchedule/components/DistributeHeader.vue
web/src/filters/index.ts
web/src/router/index.ts
web/src/store/modules/CommonInformation.ts
web/src/types/common/index.ts

refer to https://github.com/bcgov/sheriff-scheduling/pull/61 for details.

Implement Manage Types Permissions, plus changes based on feedback.

---

api/controllers/AuthController.cs
api/controllers/usermanagement/SheriffController.cs
db/configuration/PermissionConfiguration.cs
db/db.csproj
db/migrations/20201212165731_EditAndRemoveTrainingPermissions.Designer.cs
db/migrations/20201212165731_EditAndRemoveTrainingPermissions.cs
db/migrations/20201212165816_UpdatePermissions_4.Designer.cs
db/migrations/20201212165816_UpdatePermissions_4.cs
db/migrations/20201212165816_UpdatePermissions_4.sql
db/models/auth/Permission.cs
docker/docker-compose.yaml
web/package-lock.json
web/src/App.vue
web/src/components/Home.vue
web/src/components/Logout.vue
web/src/components/MyTeam/DefineRolesAccess.vue
web/src/components/MyTeam/MyTeamMembers.vue
web/src/components/MyTeam/Tabs/AddForms/AddLocationForm.vue
web/src/components/MyTeam/Tabs/IdentificationTab.vue
web/src/components/MyTeam/Tabs/LeaveTab.vue
web/src/components/MyTeam/Tabs/LocationTab.vue
web/src/components/MyTeam/Tabs/RoleAssignmentTab.vue
web/src/components/MyTeam/Tabs/TrainingTab.vue
web/src/components/NavigationTopbar.vue
web/src/components/RequestAccess.vue
web/src/router/index.ts
web/src/store/modules/CommonInformation.ts

Refer to https://github.com/bcgov/sheriff-scheduling/pull/67 for details.

Implement permissions on Location, Team member profile, and Roles pages.  Enable login permission.

---

web/package-lock.json
web/src/components/DutyRoster/DutyRoster.vue
web/src/components/DutyRoster/DutyRosterDayView.vue
web/src/components/DutyRoster/components/AddDutySlotForm.vue
web/src/components/DutyRoster/components/AddDutySlotWeekForm.vue
web/src/components/DutyRoster/components/DutyCard.vue
web/src/components/DutyRoster/components/DutyCardWeekView.vue
web/src/components/DutyRoster/components/DutyRosterAssignment.vue
web/src/components/DutyRoster/components/DutyRosterHeader.vue
web/src/components/DutyRoster/components/SheriffAvailabilityCard.vue
web/src/components/DutyRoster/components/SheriffFuelGauge.vue
web/src/store/modules/DutyRosterInformation.ts
web/src/types/DutyRoster/index.ts

Refer to https://github.com/bcgov/sheriff-scheduling/pull/70 for details

Add 12 hour view to duty roster

---

web/src/components/DutyRoster/components/DutyCard.vue
web/src/components/DutyRoster/components/DutyRosterTeamMemberCard.vue
web/src/components/MyTeam/Tabs/LeaveTab.vue
web/src/components/MyTeam/Tabs/LocationTab.vue
web/src/components/MyTeam/Tabs/TrainingTab.vue
web/src/components/ShiftSchedule/ManageSchedule.vue
web/src/components/ShiftSchedule/components/DistributeHeader.vue
web/src/router/index.ts

refer to https://github.com/bcgov/sheriff-scheduling/pull/75 for details

Resolve issues caused by tooltips in the duty-roster page, plus changes based on feedback

---

api/appsettings.json
api/infrastructure/middleware/ErrorHandlingMiddleware.cs
api/services/scheduling/DutyRosterService.cs
api/services/usermanagement/SheriffService.cs
db/migrations/20201221171338_MaxLengthComment.Designer.cs
db/migrations/20201221171338_MaxLengthComment.cs
db/models/scheduling/Assignment.cs
db/models/scheduling/Duty.cs
db/models/scheduling/Shift.cs
db/models/sheriff/SheriffTraining.cs
db/models/sheriff/abstract/SheriffEvent.cs
docker/docker-compose.yaml
web/src/components/DutyRoster/DutyRoster.vue
web/src/components/DutyRoster/DutyRosterDayView.vue
web/src/components/DutyRoster/DutyRosterWeekView.vue
web/src/components/DutyRoster/components/DutyCard.vue
web/src/components/DutyRoster/components/DutyCardWeekView.vue
web/src/components/DutyRoster/components/DutyRosterAssignment.vue
web/src/components/DutyRoster/components/DutyRosterHeader.vue
web/src/components/DutyRoster/components/DutyRosterTeamMemberCard.vue
web/src/components/DutyRoster/components/SheriffAvailabilityCard.vue
web/src/components/DutyRoster/components/SheriffFuelGauge.vue
web/src/components/MyTeam/Tabs/LeaveTab.vue
web/src/components/MyTeam/Tabs/LocationTab.vue

- Improvements to the duty roster page usability and display
- Adds functionality to display past leaves and away locations in the profile window.
Refer to https://github.com/bcgov/sheriff-scheduling/pull/77 for details

Improvements duty roster page and profile window

---

web/src/components/MyTeam/MyTeamMembers.vue
web/src/components/MyTeam/Tabs/UserSummaryTemplate.vue
web/src/components/NavigationTopbar.vue
web/src/components/ShiftSchedule/DistributeSchedule.vue
web/src/components/ShiftSchedule/components/DistributeHeader.vue
web/src/filters/index.ts

refer to https://github.com/bcgov/sheriff-scheduling/pull/83 for details

Updates based on user feedback

---

api/Program.cs
api/helpers/extensions/IQueryableExtensions.cs
api/infrastructure/authorization/DevelopmentEnvironmentClaimsFilter.cs
api/infrastructure/encryption/AesGcmXmlDecryptor.cs
api/infrastructure/encryption/AesGcmXmlEncryptor.cs
api/models/ShiftAdjustment.cs
api/services/ChesEmailService.cs
api/services/scheduling/AssignmentService.cs
web/src/App.vue
web/src/components/DutyRoster/DutyRoster.vue
web/src/components/DutyRoster/DutyRosterDayView.vue
web/src/components/DutyRoster/DutyRosterWeekView.vue
web/src/components/DutyRoster/components/DutyCardWeekView.vue
web/src/components/DutyRoster/components/DutyRosterAssignment.vue
web/src/components/DutyRoster/components/DutyRosterHeader.vue
web/src/components/DutyRoster/components/DutyRosterTeamMemberCard.vue
web/src/components/ManageTypes/AssignmentTypes.vue
web/src/components/ManageTypes/LeaveTrainingTypes.vue
web/src/components/MyTeam/DefineRolesAccess.vue
web/src/components/MyTeam/MyTeamMembers.vue
web/src/components/MyTeam/Tabs/LeaveTab.vue
web/src/components/MyTeam/Tabs/RoleAssignmentTab.vue
web/src/components/MyTeam/Tabs/TrainingTab.vue
web/src/components/ShiftSchedule/DistributeSchedule.vue
web/src/components/ShiftSchedule/ManageSchedule.vue
web/src/components/ShiftSchedule/components/ScheduleHeader.vue
web/src/components/ShiftSchedule/components/TeamMemberCard.vue
web/src/types/ShiftSchedule/index.ts

Refer to https://github.com/bcgov/sheriff-scheduling/pull/88 for details.

Enable accessing profile windows from duty-roster and manage-shift pages, plus additional enhancements.

---

api/services/scheduling/DutyRosterService.cs
api/services/scheduling/ShiftService.cs
web/src/components/DutyRoster/DutyRosterWeekView.vue
web/src/components/DutyRoster/components/DutyRosterAssignment.vue
web/src/components/ShiftSchedule/ManageSchedule.vue

Refer to https://github.com/bcgov/sheriff-scheduling/pull/92 for details.

Fixes for SS-688, SS-689, SS-690, SS-693 and SS-694

---

api/services/scheduling/ShiftService.cs

Fix for loaned in sheriffs import.

Fix for loaned in sheriffs import.

---

web/package-lock.json
web/package.json

Reverts bcgov/sheriff-scheduling#200

Revert "Dependabot/npm and yarn/web/json5 and json5 and vue/cli service 2.2.3"

---

api/models/dto/TrainingReportSearchDto.cs
api/services/usermanagement/TrainingService.cs
web/src/components/MyTeam/Tabs/TrainingTab.vue
web/src/components/MyTeam/ViewReports.vue
web/src/types/MyTeam/index.ts
web/src/types/common/index.ts

SS-821: filter the report screen by team member/search by team member
- Add a button on the team member profile trainings tab to go to reports screen and filter by that team member

SS-821: filter the report screen by team member/search by team member

---

web/src/components/MyTeam/ViewReports.vue

SS-821: get sheriffs after getting training types to prevent training type field error

SS-821: get sheriffs after getting training types to prevent training types field error

---

api/controllers/usermanagement/SheriffController.cs
api/services/scheduling/ShiftService.cs
api/services/usermanagement/SheriffService.cs
web/src/components/MyTeam/Tabs/TrainingTab.vue

- Allow trainings time to overlap on same date and time
- Allow shifts to be schedules on same date and time as trainings (dont check conflicts)

SS-815: Allow entering shifts and trainings separately

---

api/models/dto/TrainingReportDto.cs
api/services/usermanagement/TrainingService.cs
web/src/components/MyTeam/ViewReports.vue
web/src/types/MyTeam/index.ts

SS-824 add region column and sort by region for csv export
